apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-hello-app-pvc
  namespace: default
  labels:
    app: nginx-hello-app
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
      
