---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-front-app
spec:
  selector:
    matchLabels:
      app: nginx-front-app # has to match .spec.template.metadata.labels
  serviceName: "nginx-front-app-svc"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx-front-app # has to match .spec.selector.matchLabels
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-front-app
        image: docker.io/mrdojojo/nginx-hello-app:1.1-arm64
        #image: docker.io/mrdojojo/nginx-hello-app:1.1-x86-64
        ports:
        - containerPort: 8080
          name: nginx-front-app
        volumeMounts:
        - name: nginx-front-app-pvc   #storage
          mountPath: "/usr/share/nginx/html"
  volumeClaimTemplates:
  - metadata:
      name: nginx-front-app-pvc
      labels:
        app: nginx-front-app
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "pd-standard"
      resources:
        requests:
          storage: 100Gi
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-front-app-svc
  labels:
    app: nginx-front-app
spec:
  type: NodePort
  selector:
    app: nginx-front-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-front-app-ingress
spec:
  defaultBackend:
    service:
      name: nginx-front-app-svc
      port:
        number: 8080
  rules:
  - http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-front-app-svc
            port:
              number: 8080
